// Sign in Phase

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

// Sign up Phase

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

// Instagram login Phase

export const INSTAGRAM_REQUEST = 'INSTAGRAM_REQUEST';
export const INSTAGRAM_SUCCESS = 'INSTAGRAM_SUCCESS';
export const INSTAGRAM_FAILURE = 'INSTAGRAM_FAILURE';

// Getting user Phase

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

// Updating profile Phase

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// Upload photo profile

export const UPLOAD_PROFILE_PHOTO = 'UPDATE_PROFILE_PHOTO';
export const UPLOAD_PROFILE_PHOTO_SUCCESS = 'UPLOAD_PROFILE_PHOTO_SUCCESS';
export const UPLOAD_PROFILE_PHOTO_FAILURE = 'UPLOAD_PROFILE_PHOTO_FAILURE';

// Upload Cover Photo

export const UPLOAD_COVER_PHOTO = 'UPLOAD_COVER_PHOTO';
export const UPLOAD_COVER_PHOTO_SUCCESS = 'UPLOAD_COVER_PHOTO_SUCCESS';
export const UPLOAD_COVER_PHOTO_FAILURE = 'UPLOAD_COVER_PHOTO_FAILURE';

// Create Post Phase

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

// Fetching Post Data

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

// Checking Connection

export const CHECK_CONNECTION_STATUS = 'CHECK_CONNECTION_STATUS';